package org.example;

import org.example.autogenerated_todelete.table_QUT_PRM_DTL;
import org.example.autogenerated_todelete.table_QUT_PRM_MST;
import org.example.autogenerated_todelete.table_WAREHOUSE;
import org.example.select_helper.*;
import org.example.test.Vec;

public class Main {
    public static void main(String[] args) {
        Vec vec = new Vec(1, 2, 3);
        Vec vec2 = new Vec(1, 2, 3);
//        Vec vec3 = vec + vec2;

//        System.out.println(vec3.x);


        table_QUT_PRM_MST master = new table_QUT_PRM_MST();
        table_QUT_PRM_DTL detail = new table_QUT_PRM_DTL();
        table_WAREHOUSE warehouse = new table_WAREHOUSE();

        TempTable tempTable = DBSelectHelper.SELECT_ALL()
                .FROM(master)
                .WHERE(master.QUOT_NO.equal(0))
                .LIMIT(1).toTable("PMR_TEMP");

        DBSelectHelper
                .SELECT(
                        DB.MAX(master.BY_COMP_QTY),
                        master.QUOT_NO.as("NO"), detail.QT_QTY.as("PRM_QTY"), tempTable.getColumn(master.BY_COMP_QTY)
                )
                .WHERE(
                        tempTable.getColumn(master.QUOT_NO).equal(1),
                        master.QUOT_NO.equal("D456").or(master.CC_CODE.equal(1)),
                        master.F_DATE.equal(detail.F_AMT)
                )
                .GROUP_BY(
                        master.QUOT_NO,
                        detail.RCRD_NO
                )
                .WHERE(
                        master.BY_COMP_QTY.equal(1)
                )
                .ORDER_BY(
                        master.CC_CODE.asc(),
                        master.F_DATE.desc(),
                        master.F_TIME
                )
                .LIMIT(1)
                .log("LIMIT");
    }
}