package org.example;

import org.example.autogenerated_todelete.table_QUT_PRM_DTL;
import org.example.autogenerated_todelete.table_QUT_PRM_MST;
import org.example.select_helper.DBSelectHelper;
import org.example.select_helper.column.Column;

import static org.example.select_helper.DBSelectHelper.SELECT;

public class Main {
    public static void main(String[] args) {
        table_QUT_PRM_MST master = new table_QUT_PRM_MST();
        table_QUT_PRM_DTL detail = new table_QUT_PRM_DTL();

        String string = DBSelectHelper
                .SELECT(
                        master.QUOT_NO,
                        master.QUOT_SER
                )
                .FROM(
                        master, detail
                )
                .WHERE(
                        master.APPRVD_FREEQTY_AS_DSCNT.between(1, 2)
                )
                .GROUP_BY(
                        master.QUOT_NO,
                        detail.RCRD_NO
                ).toString();

        System.out.println(
                string
        );
    }
}