package org.example.autogenerated_todelete;

import org.example.select_helper.Table;
import org.example.select_helper.column.Column;

public final class table_QUT_PRM_DTL extends Table {
    public table_QUT_PRM_DTL() {
        super("QUT_PRM_DTL");
    }

    public Column QUOT_SER = new Column(this, "QUOT_SER");
    ;

    public Column RCRD_NO = new Column(this, "RCRD_NO");
    ;

    public Column QUOT_NO = new Column(this, "QUOT_NO");
    ;

    public Column I_CODE = new Column(this, "I_CODE");
    ;

    public Column ITM_UNT = new Column(this, "ITM_UNT");
    ;

    public Column P_SIZE = new Column(this, "P_SIZE");
    ;

    public Column I_PRICE = new Column(this, "I_PRICE");
    ;

    public Column BARCODE = new Column(this, "BARCODE");
    ;

    public Column F_QTY = new Column(this, "F_QTY");
    ;

    public Column T_QTY = new Column(this, "T_QTY");
    ;

    public Column F_AMT = new Column(this, "F_AMT");
    ;

    public Column T_AMT = new Column(this, "T_AMT");
    ;

    public Column DISC_TYPE = new Column(this, "DISC_TYPE");
    ;

    public Column DISC_AMT_PER = new Column(this, "DISC_AMT_PER");
    ;

    public Column QT_I_CODE = new Column(this, "QT_I_CODE");
    ;

    public Column FREE_QTY = new Column(this, "FREE_QTY");
    ;

    public Column QT_ITM_UNT = new Column(this, "QT_ITM_UNT");
    ;

    public Column QT_QTY = new Column(this, "QT_QTY");
    ;

    public Column W_CODE = new Column(this, "W_CODE");
    ;

    public Column WHG_CODE = new Column(this, "WHG_CODE");
    ;

    public Column CNTRY_NO = new Column(this, "CNTRY_NO");
    ;

    public Column PROV_NO = new Column(this, "PROV_NO");
    ;

    public Column CITY_NO = new Column(this, "CITY_NO");
    ;

    public Column R_CODE = new Column(this, "R_CODE");
    ;

    public Column CARD_AMT = new Column(this, "CARD_AMT");
    ;

    public Column COMP_QTY = new Column(this, "COMP_QTY");
    ;

    public Column EXPIRE_DATE = new Column(this, "EXPIRE_DATE");
    ;

    public Column BATCH_NO = new Column(this, "BATCH_NO");
    ;

    public Column C_CODE = new Column(this, "C_CODE");
    ;

    public Column C_GROUP_CODE = new Column(this, "C_GROUP_CODE");
    ;

    public Column C_CLASS = new Column(this, "C_CLASS");
    ;

    public Column C_DEGREE = new Column(this, "C_DEGREE");
    ;

    public Column G_CODE = new Column(this, "G_CODE");
    ;

    public Column MNG_CODE = new Column(this, "MNG_CODE");
    ;

    public Column SUBG_CODE = new Column(this, "SUBG_CODE");
    ;

    public Column ASSISTANT_NO = new Column(this, "ASSISTANT_NO");
    ;

    public Column DETAIL_NO = new Column(this, "DETAIL_NO");
    ;

    public Column GROUP_NO = new Column(this, "GROUP_NO");
    ;

    public Column ITEM_TYPE = new Column(this, "ITEM_TYPE");
    ;

    public Column GRP_CLASS_CODE = new Column(this, "GRP_CLASS_CODE");
    ;

    public Column PRM_GRP_NO = new Column(this, "PRM_GRP_NO");
    ;

    public Column BANK_NO = new Column(this, "BANK_NO");
    ;

    public Column MAX_QT_QTY_DOC = new Column(this, "MAX_QT_QTY_DOC");
    ;

    public Column VER_NO = new Column(this, "VER_NO");
    ;
}
