package org.example.autogenerated_todelete;

import org.example.select_helper.Table;
import org.example.select_helper.column.Column;

public  class table_WAREHOUSE extends Table {
    public table_WAREHOUSE() {
        super("WAREHOUSE");
    }

    public Column W_CODE = new Column(this, "W_CODE");
    ;

    public Column WCODE_TYPE = new Column(this, "WCODE_TYPE");
    ;

    public Column W_NAME = new Column(this, "W_NAME");
    ;

    public Column W_E_NAME = new Column(this, "W_E_NAME");
    ;

    public Column WHG_CODE = new Column(this, "WHG_CODE");
    ;

    public Column CNTRY_NO = new Column(this, "CNTRY_NO");
    ;

    public Column PROV_NO = new Column(this, "PROV_NO");
    ;

    public Column CITY_NO = new Column(this, "CITY_NO");
    ;

    public Column R_CODE = new Column(this, "R_CODE");
    ;

    public Column MAIN_WCODE = new Column(this, "MAIN_WCODE");
    ;

    public Column TRNSFR_WCODE_FLG = new Column(this, "TRNSFR_WCODE_FLG");
    ;

    public Column ADD_FLAG = new Column(this, "ADD_FLAG");
    ;

    public Column VER_NO = new Column(this, "VER_NO");
    ;

    public Column VIEW_FLAG = new Column(this, "VIEW_FLAG");
    ;

    public Column GRP_CODE = new Column(this, "GRP_CODE");
    ;
}
