package org.example.autogenerated_todelete;

import org.example.select_helper.Table;
import org.example.select_helper.column.Column;

public final class table_QUT_PRM_MST extends Table {
  public table_QUT_PRM_MST() {
    super("QUT_PRM_MST");
  }

  public Column QUOT_NO = new Column("QUT_PRM_MST","QUOT_NO");
  ;

  public Column QUOT_SER = new Column("QUT_PRM_MST","QUOT_SER");
  ;

  public Column QUOT_CUR = new Column("QUT_PRM_MST","QUOT_CUR");
  ;

  public Column F_DATE = new Column("QUT_PRM_MST","F_DATE");
  ;

  public Column T_DATE = new Column("QUT_PRM_MST","T_DATE");
  ;

  public Column F_TIME = new Column("QUT_PRM_MST","F_TIME");
  ;

  public Column T_TIME = new Column("QUT_PRM_MST","T_TIME");
  ;

  public Column CC_CODE = new Column("QUT_PRM_MST","CC_CODE");
  ;

  public Column W_CODE = new Column("QUT_PRM_MST","W_CODE");
  ;

  public Column FLD_DAY1 = new Column("QUT_PRM_MST","FLD_DAY1");
  ;

  public Column FLD_DAY2 = new Column("QUT_PRM_MST","FLD_DAY2");
  ;

  public Column FLD_DAY3 = new Column("QUT_PRM_MST","FLD_DAY3");
  ;

  public Column FLD_DAY4 = new Column("QUT_PRM_MST","FLD_DAY4");
  ;

  public Column FLD_DAY5 = new Column("QUT_PRM_MST","FLD_DAY5");
  ;

  public Column FLD_DAY6 = new Column("QUT_PRM_MST","FLD_DAY6");
  ;

  public Column FLD_DAY7 = new Column("QUT_PRM_MST","FLD_DAY7");
  ;

  public Column QT_PRM_TYPE = new Column("QUT_PRM_MST","QT_PRM_TYPE");
  ;

  public Column QT_PRM_METHOD = new Column("QUT_PRM_MST","QT_PRM_METHOD");
  ;

  public Column QT_PRM_WC_TYPE = new Column("QUT_PRM_MST","QT_PRM_WC_TYPE");
  ;

  public Column QT_PRM_CST_TYPE = new Column("QUT_PRM_MST","QT_PRM_CST_TYPE");
  ;

  public Column BY_COMP_QTY = new Column("QUT_PRM_MST","BY_COMP_QTY");
  ;

  public Column CALC_ALL_SLIDES = new Column("QUT_PRM_MST","CALC_ALL_SLIDES");
  ;

  public Column BILL_DOC_TYPE = new Column("QUT_PRM_MST","BILL_DOC_TYPE");
  ;

  public Column APPRVD_FREEQTY_AS_DSCNT = new Column("QUT_PRM_MST","APPRVD_FREEQTY_AS_DSCNT");
  ;

  public Column QT_PRM_ITM_TYPE = new Column("QUT_PRM_MST","QT_PRM_ITM_TYPE");
  ;

  public Column INACTIVE = new Column("QUT_PRM_MST","INACTIVE");
  ;

  public Column CMLTV_MNTH_FLG = new Column("QUT_PRM_MST","CMLTV_MNTH_FLG");
  ;

  public Column VER_NO = new Column("QUT_PRM_MST","VER_NO");
  ;

  public Column QT_PRM_TYPE_L_NM = new Column("QUT_PRM_MST","QT_PRM_TYPE_L_NM");
  ;

  public Column QT_PRM_TYPE_F_NM = new Column("QUT_PRM_MST","QT_PRM_TYPE_F_NM");
  ;

  public Column QT_PRM_METHOD_L_NM = new Column("QUT_PRM_MST","QT_PRM_METHOD_L_NM");
  ;

  public Column QT_PRM_METHOD_F_NM = new Column("QUT_PRM_MST","QT_PRM_METHOD_F_NM");
  ;

  public Column selected = new Column("QUT_PRM_MST","selected");
  ;

  public Column DisplayName = new Column("QUT_PRM_MST","DisplayName");
  ;
}
