package org.example.autogenerated_todelete;

import org.example.select_helper.Table;
import org.example.select_helper.column.Column;

public final class table_WAREHOUSE extends Table {
    public table_WAREHOUSE() {
        super("WAREHOUSE");
    }

    public Column W_CODE = new Column("WAREHOUSE", "W_CODE");
    ;

    public Column WCODE_TYPE = new Column("WAREHOUSE", "WCODE_TYPE");
    ;

    public Column W_NAME = new Column("WAREHOUSE", "W_NAME");
    ;

    public Column W_E_NAME = new Column("WAREHOUSE", "W_E_NAME");
    ;

    public Column WHG_CODE = new Column("WAREHOUSE", "WHG_CODE");
    ;

    public Column CNTRY_NO = new Column("WAREHOUSE", "CNTRY_NO");
    ;

    public Column PROV_NO = new Column("WAREHOUSE", "PROV_NO");
    ;

    public Column CITY_NO = new Column("WAREHOUSE", "CITY_NO");
    ;

    public Column R_CODE = new Column("WAREHOUSE", "R_CODE");
    ;

    public Column MAIN_WCODE = new Column("WAREHOUSE", "MAIN_WCODE");
    ;

    public Column TRNSFR_WCODE_FLG = new Column("WAREHOUSE", "TRNSFR_WCODE_FLG");
    ;

    public Column ADD_FLAG = new Column("WAREHOUSE", "ADD_FLAG");
    ;

    public Column VER_NO = new Column("WAREHOUSE", "VER_NO");
    ;

    public Column VIEW_FLAG = new Column("WAREHOUSE", "VIEW_FLAG");
    ;

    public Column GRP_CODE = new Column("WAREHOUSE", "GRP_CODE");
    ;
}
